MainBox:

<Label>
    color: 0.93, 0.94, 0.96, 1 

<MainBox>
    orientation: "vertical"

    canvas.before:
        Color:
            rgba: (0.18, 0.20, 0.25, 1) # Nord 0

        Rectangle: 
            pos: self.pos
            size: self.size
        
    Label:
        text: "Move It"
        font_size: dp(20)
    
    Label:
        text: ""
        font_size: dp(10)
        
    Label:
        text: root.moving

    Label:
        text: root.countdown