-- Cambios de nombre
ALTER TABLE REL_TIPO_COMPONENTE_PROPIEDAD RENAME COLUMN OPCIONAL to OBLIGATORIO;
ALTER TABLE REGLAS_COMPOSICION RENAME COLUMN OPCIONAL to OBLIGATORIO;
ALTER TABLE TIPO_DOCUMENTO_X_ACTIVIDAD RENAME COLUMN OPCIONAL to OBLIGATORIO;

-- Cambios de datos
UPDATE REL_TIPO_COMPONENTE_PROPIEDAD SET OBLIGATORIO = ABS(OBLIGATORIO-1);
UPDATE REGLAS_COMPOSICION SET OBLIGATORIO = ABS(OBLIGATORIO-1);
UPDATE TIPO_DOCUMENTO_X_ACTIVIDAD SET OBLIGATORIO = ABS(OBLIGATORIO-1);

-- Campos nuevos
ALTER TABLE TIPO_DOCUMENTO_X_ACTIVIDAD ADD VISIBLE char(1) NULL;
ALTER TABLE PROPIEDAD ADD VALOR_CONSTANTE varchar(2000) NULL;

-- Restriccion menos
ALTER TABLE VAL_OBJ_NEG_X_ACT DROP CONSTRAINT SYS_C0027375;
