-- Create the tablepace for the user
create tablespace PROC_PCPTS
  logging
  datafile '/opt/oracle/app/oracle/oradata/orcl/proc_pcpts.dbf'
  size 32m 
  autoextend on 
  next 32m maxsize 2048m
  extent management local;

-- Create the user 
create user PSCPCP01
  identified by ""
  default tablespace PROC_PCPTS
  temporary tablespace TEMP
  profile DEFAULT
  password expire
  quota unlimited on proc_pcpts;

-- Grant/Revoke role privileges 
grant adm_parallel_execute_task to PSCPCP01;
grant apex_administrator_role to PSCPCP01;
grant aq_administrator_role to PSCPCP01;
grant aq_user_role to PSCPCP01;
grant authenticateduser to PSCPCP01;
grant connect to PSCPCP01;
grant csw_usr_role to PSCPCP01;
grant ctxapp to PSCPCP01;
grant cwm_user to PSCPCP01;
grant datapump_exp_full_database to PSCPCP01;
grant datapump_imp_full_database to PSCPCP01;
grant dba to PSCPCP01;
grant dbfs_role to PSCPCP01;
grant delete_catalog_role to PSCPCP01;
grant ejbclient to PSCPCP01;
grant execute_catalog_role to PSCPCP01;
grant exp_full_database to PSCPCP01;
grant gather_system_statistics to PSCPCP01;
grant hs_admin_execute_role to PSCPCP01;
grant hs_admin_role to PSCPCP01;
grant hs_admin_select_role to PSCPCP01;
grant imp_full_database to PSCPCP01;
grant java_admin to PSCPCP01;
grant javadebugpriv to PSCPCP01;
grant java_deploy to PSCPCP01;
grant javaidpriv to PSCPCP01;
grant javasyspriv to PSCPCP01;
grant javauserpriv to PSCPCP01;
grant jmxserver to PSCPCP01;
grant logstdby_administrator to PSCPCP01;
grant mgmt_user to PSCPCP01;
grant oem_advisor to PSCPCP01;
grant oem_monitor to PSCPCP01;
grant olap_dba to PSCPCP01;
grant olapi_trace_user to PSCPCP01;
grant olap_user to PSCPCP01;
grant olap_xs_admin to PSCPCP01;
grant ordadmin to PSCPCP01;
grant owb$client to PSCPCP01;
grant owb_designcenter_view to PSCPCP01;
grant owb_user to PSCPCP01;
grant recovery_catalog_owner to PSCPCP01;
grant resource to PSCPCP01;
grant scheduler_admin to PSCPCP01;
grant select_catalog_role to PSCPCP01;
grant spatial_csw_admin to PSCPCP01;
grant spatial_wfs_admin to PSCPCP01;
grant wfs_usr_role to PSCPCP01;
grant wm_admin_role to PSCPCP01;
grant xdbadmin to PSCPCP01;
grant xdb_set_invoker to PSCPCP01;
grant xdb_webservices to PSCPCP01;
grant xdb_webservices_over_http to PSCPCP01;
grant xdb_webservices_with_public to PSCPCP01;

-- Grant/Revoke system privileges 
grant administer any sql tuning set to PSCPCP01;
grant administer database trigger to PSCPCP01;
grant administer sql management object to PSCPCP01;
grant administer sql tuning set to PSCPCP01;
grant advisor to PSCPCP01;
grant alter any assembly to PSCPCP01;
grant alter any cluster to PSCPCP01;
grant alter any cube to PSCPCP01;
grant alter any cube dimension to PSCPCP01;
grant alter any dimension to PSCPCP01;
grant alter any edition to PSCPCP01;
grant alter any evaluation context to PSCPCP01;
grant alter any index to PSCPCP01;
grant alter any indextype to PSCPCP01;
grant alter any library to PSCPCP01;
grant alter any materialized view to PSCPCP01;
grant alter any mining model to PSCPCP01;
grant alter any operator to PSCPCP01;
grant alter any outline to PSCPCP01;
grant alter any procedure to PSCPCP01;
grant alter any role to PSCPCP01;
grant alter any rule to PSCPCP01;
grant alter any rule set to PSCPCP01;
grant alter any sequence to PSCPCP01;
grant alter any sql profile to PSCPCP01;
grant alter any table to PSCPCP01;
grant alter any trigger to PSCPCP01;
grant alter any type to PSCPCP01;
grant alter database to PSCPCP01;
grant alter database link to PSCPCP01;
grant alter profile to PSCPCP01;
grant alter public database link to PSCPCP01;
grant alter resource cost to PSCPCP01;
grant alter rollback segment to PSCPCP01;
grant alter session to PSCPCP01;
grant alter system to PSCPCP01;
grant alter tablespace to PSCPCP01;
grant alter user to PSCPCP01;
grant analyze any to PSCPCP01;
grant analyze any dictionary to PSCPCP01;
grant audit any to PSCPCP01;
grant audit system to PSCPCP01;
grant backup any table to PSCPCP01;
grant become user to PSCPCP01;
grant change notification to PSCPCP01;
grant comment any mining model to PSCPCP01;
grant comment any table to PSCPCP01;
grant create any assembly to PSCPCP01;
grant create any cluster to PSCPCP01;
grant create any context to PSCPCP01;
grant create any cube to PSCPCP01;
grant create any cube build process to PSCPCP01;
grant create any cube dimension to PSCPCP01;
grant create any dimension to PSCPCP01;
grant create any directory to PSCPCP01;
grant create any edition to PSCPCP01;
grant create any evaluation context to PSCPCP01;
grant create any index to PSCPCP01;
grant create any indextype to PSCPCP01;
grant create any job to PSCPCP01;
grant create any library to PSCPCP01;
grant create any materialized view to PSCPCP01;
grant create any measure folder to PSCPCP01;
grant create any mining model to PSCPCP01;
grant create any operator to PSCPCP01;
grant create any outline to PSCPCP01;
grant create any procedure to PSCPCP01;
grant create any rule to PSCPCP01;
grant create any rule set to PSCPCP01;
grant create any sequence to PSCPCP01;
grant create any sql profile to PSCPCP01;
grant create any synonym to PSCPCP01;
grant create any table to PSCPCP01;
grant create any trigger to PSCPCP01;
grant create any type to PSCPCP01;
grant create any view to PSCPCP01;
grant create assembly to PSCPCP01;
grant create cluster to PSCPCP01;
grant create cube to PSCPCP01;
grant create cube build process to PSCPCP01;
grant create cube dimension to PSCPCP01;
grant create database link to PSCPCP01;
grant create dimension to PSCPCP01;
grant create evaluation context to PSCPCP01;
grant create external job to PSCPCP01;
grant create indextype to PSCPCP01;
grant create job to PSCPCP01;
grant create library to PSCPCP01;
grant create materialized view to PSCPCP01;
grant create measure folder to PSCPCP01;
grant create mining model to PSCPCP01;
grant create operator to PSCPCP01;
grant create procedure to PSCPCP01;
grant create profile to PSCPCP01;
grant create public database link to PSCPCP01;
grant create public synonym to PSCPCP01;
grant create role to PSCPCP01;
grant create rollback segment to PSCPCP01;
grant create rule to PSCPCP01;
grant create rule set to PSCPCP01;
grant create sequence to PSCPCP01;
grant create session to PSCPCP01;
grant create synonym to PSCPCP01;
grant create table to PSCPCP01;
grant create tablespace to PSCPCP01;
grant create trigger to PSCPCP01;
grant create type to PSCPCP01;
grant create user to PSCPCP01;
grant create view to PSCPCP01;
grant debug any procedure to PSCPCP01;
grant debug connect session to PSCPCP01;
grant delete any cube dimension to PSCPCP01;
grant delete any measure folder to PSCPCP01;
grant delete any table to PSCPCP01;
grant dequeue any queue to PSCPCP01;
grant drop any assembly to PSCPCP01;
grant drop any cluster to PSCPCP01;
grant drop any context to PSCPCP01;
grant drop any cube to PSCPCP01;
grant drop any cube build process to PSCPCP01;
grant drop any cube dimension to PSCPCP01;
grant drop any dimension to PSCPCP01;
grant drop any directory to PSCPCP01;
grant drop any edition to PSCPCP01;
grant drop any evaluation context to PSCPCP01;
grant drop any index to PSCPCP01;
grant drop any indextype to PSCPCP01;
grant drop any library to PSCPCP01;
grant drop any materialized view to PSCPCP01;
grant drop any measure folder to PSCPCP01;
grant drop any mining model to PSCPCP01;
grant drop any operator to PSCPCP01;
grant drop any outline to PSCPCP01;
grant drop any procedure to PSCPCP01;
grant drop any role to PSCPCP01;
grant drop any rule to PSCPCP01;
grant drop any rule set to PSCPCP01;
grant drop any sequence to PSCPCP01;
grant drop any sql profile to PSCPCP01;
grant drop any synonym to PSCPCP01;
grant drop any table to PSCPCP01;
grant drop any trigger to PSCPCP01;
grant drop any type to PSCPCP01;
grant drop any view to PSCPCP01;
grant drop profile to PSCPCP01;
grant drop public database link to PSCPCP01;
grant drop public synonym to PSCPCP01;
grant drop rollback segment to PSCPCP01;
grant drop tablespace to PSCPCP01;
grant drop user to PSCPCP01;
grant enqueue any queue to PSCPCP01;
grant execute any assembly to PSCPCP01;
grant execute any class to PSCPCP01;
grant execute any evaluation context to PSCPCP01;
grant execute any indextype to PSCPCP01;
grant execute any library to PSCPCP01;
grant execute any operator to PSCPCP01;
grant execute any procedure to PSCPCP01;
grant execute any program to PSCPCP01;
grant execute any rule to PSCPCP01;
grant execute any rule set to PSCPCP01;
grant execute any type to PSCPCP01;
grant execute assembly to PSCPCP01;
grant exempt access policy to PSCPCP01;
grant exempt identity policy to PSCPCP01;
grant export full database to PSCPCP01;
grant flashback any table to PSCPCP01;
grant flashback archive administer to PSCPCP01;
grant force any transaction to PSCPCP01;
grant force transaction to PSCPCP01;
grant global query rewrite to PSCPCP01;
grant grant any object privilege to PSCPCP01;
grant grant any privilege to PSCPCP01;
grant grant any role to PSCPCP01;
grant import full database to PSCPCP01;
grant insert any cube dimension to PSCPCP01;
grant insert any measure folder to PSCPCP01;
grant insert any table to PSCPCP01;
grant lock any table to PSCPCP01;
grant manage any file group to PSCPCP01;
grant manage any queue to PSCPCP01;
grant manage file group to PSCPCP01;
grant manage scheduler to PSCPCP01;
grant manage tablespace to PSCPCP01;
grant merge any view to PSCPCP01;
grant on commit refresh to PSCPCP01;
grant query rewrite to PSCPCP01;
grant read any file group to PSCPCP01;
grant restricted session to PSCPCP01;
grant resumable to PSCPCP01;
grant select any cube to PSCPCP01;
grant select any cube dimension to PSCPCP01;
grant select any dictionary to PSCPCP01;
grant select any mining model to PSCPCP01;
grant select any sequence to PSCPCP01;
grant select any table to PSCPCP01;
grant select any transaction to PSCPCP01;
grant under any table to PSCPCP01;
grant under any type to PSCPCP01;
grant under any view to PSCPCP01;
grant unlimited tablespace to PSCPCP01;
grant update any cube to PSCPCP01;
grant update any cube build process to PSCPCP01;
grant update any cube dimension to PSCPCP01;
grant update any table to PSCPCP01;

-- Create directory for import
create or replace directory RUTA_EXP as '/opt/oracle/datos-1.6';
