VARIABLE cur REFCURSOR

DECLARE
  curReturn SYS_REFCURSOR;
  CINICIO CONSTANT VARCHAR2(10) := '01-09-2012';
  CFINAL CONSTANT VARCHAR2(10) := '30-09-2012';

BEGIN
  CURRETURN := PKG_REPCOSTEO.FVTA_SEMANAS (CINICIO, CFINAL);
--  CURRETURN := PKG_REPCOSTEO.FNRPTMARGEN (CINICIO, CFINAL);
  :cur := curReturn;
END;
/

PRINT cur;
